import { expect, test } from '@playwright/test';

test('approved skins, focus, scrolling, resizing, and drawer preserve a usable menu', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/fixture.html');
  await expect(page.getByRole('heading', { name: 'Malware triage' })).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: testInfo.outputPath('main-1000x680.png') });
  const frame = page.getByRole('region', { name: 'Loadbot menu' });
  expect(await frame.evaluate((element) => getComputedStyle(element).borderImageSlice)).toBe('12 fill');
  const projects = page.getByRole('group', { name: 'Projects', exact: true });
  const first = projects.getByRole('button', { name: 're-toolkit personal' });
  const selectedSkin = await first.evaluate((element) => getComputedStyle(element).borderImageSource);
  await first.hover();
  expect(await first.evaluate((element) => getComputedStyle(element).borderImageSource)).toBe(selectedSkin);
  await first.focus();
  await page.keyboard.press('ArrowDown');
  await expect(projects.getByRole('button', { name: 'radio personal' })).toBeFocused();
  await expect(first).toHaveAttribute('aria-pressed', 'true');
  await page.screenshot({ path: testInfo.outputPath('keyboard-focus.png') });
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', { name: 'Inspect recording' })).toBeVisible();
  await first.click();
  await page.getByLabel('Input folder *').focus();
  await page.screenshot({ path: testInfo.outputPath('input-focus.png') });
  await page.getByRole('button', { name: 'Use sample input folder' }).click();
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('region', { name: 'Terminal placeholder' })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('drawer-1000x680.png') });
  await page.getByRole('button', { name: 'Terminal', exact: true }).click();
  await expect(page.getByLabel('Input folder *')).toHaveValue('samples/');
  await expect(page.getByRole('checkbox')).toBeChecked();
  await page.setViewportSize({ width: 722, height: 480 });
  await page.screenshot({ path: testInfo.outputPath('main-722x480.png') });
  await page.setViewportSize({ width: 1000, height: 680 });
  await projects.getByRole('button', { name: 'research-tools-with-a-long-project-name community' }).click();
  const shortcuts = page.getByRole('group', { name: 'Shortcuts', exact: true });
  await shortcuts.getByRole('button').first().focus();
  await page.keyboard.press('End');
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', { name: 'Review sample 18' })).toBeVisible();
  expect(await shortcuts.evaluate((element) => element.scrollTop)).toBeGreaterThan(0);
  await shortcuts.getByRole('button').first().click();
  await page.screenshot({ path: testInfo.outputPath('long-labels.png') });
  for (const size of [{ width: 722, height: 480 }, { width: 420, height: 480 }]) {
    await page.setViewportSize(size);
    await page.getByRole('button', { name: 'Terminal', exact: true }).click();
    await expect(page.getByRole('region', { name: 'Terminal placeholder' })).toBeVisible();
    await page.getByRole('button', { name: 'RUN SHORTCUT' }).scrollIntoViewIfNeeded();
    await expect(page.getByRole('button', { name: 'RUN SHORTCUT' })).toBeInViewport();
    await expect(page.getByRole('button', { name: 'Terminal', exact: true })).toBeInViewport();
    expect(await frame.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`small-drawer-${size.width}.png`) });
    await page.getByRole('button', { name: 'Terminal', exact: true }).click();
  }
  expect(errors).toEqual([]);
});

test('three splitters drag, clamp, persist, and reset independently', async ({ page }) => {
  await page.goto('/fixture.html');
  const projects = page.getByRole('separator', { name: 'Resize projects pane' });
  const shortcuts = page.getByRole('separator', { name: 'Resize shortcuts and selected shortcut' });
  const terminal = page.getByRole('separator', { name: 'Resize terminal pane' });
  await expect(projects).toHaveAttribute('aria-valuenow', '260');
  await expect(shortcuts).toHaveAttribute('aria-valuenow', '210');
  await expect(terminal).toHaveAttribute('aria-valuenow', '140');
  const boundary = (await projects.boundingBox())!;
  await page.mouse.move(boundary.x + 2, boundary.y + 4);
  await page.mouse.down();
  await page.mouse.move(boundary.x + 82, boundary.y + 4);
  await page.mouse.up();
  await expect(projects).toHaveAttribute('aria-valuenow', '340');
  await shortcuts.focus();
  await page.keyboard.press('ArrowDown');
  await expect(shortcuts).toHaveAttribute('aria-valuenow', '222');
  await terminal.focus();
  await page.keyboard.press('ArrowUp');
  await expect(terminal).toHaveAttribute('aria-valuenow', '152');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('loadbot.workspace.panes.v1')!))).toEqual({
    version: 1, projects: 340, shortcuts: 222, terminal: 152,
  });
  await page.reload();
  await expect(projects).toHaveAttribute('aria-valuenow', '340');
  await projects.dblclick();
  await expect(projects).toHaveAttribute('aria-valuenow', '260');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('loadbot.workspace.panes.v1')!).projects)).toBe(260);
  await page.reload();
  await expect(projects).toHaveAttribute('aria-valuenow', '260');
});

test('development overlay owns bounds, close, and keyboard focus without Tauri', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1200, height: 850 });
  await page.goto('/embed.html');
  await expect(page.getByRole('heading', { name: 'Malware triage' })).toBeVisible();
  expect(await page.evaluate(() => '__TAURI_INTERNALS__' in window)).toBe(false);
  const container = page.locator('.embedding-container');
  const menu = page.getByRole('region', { name: 'Loadbot menu' });
  const parentBox = (await container.boundingBox())!;
  const menuBox = (await menu.boundingBox())!;
  expect(menuBox).toEqual(parentBox);
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: testInfo.outputPath('parent-overlay.png') });
  await page.getByRole('button', { name: 'Close Loadbot menu' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Open Loadbot overlay' })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
});
